demo/Models/ArtistDetails.cs
using System;

namespace demo.Models
{
    public class ArtistDetails
    {
        public int djid { get; set; }
        public String name { get; set; }
        public String country { get; set; }
        public String labels { get; set; }
        public String website { get; set; }
        public String raProfile { get; set; }
        public String twitter { get; set; }
        public String facebook { get; set; }
        public String discogs { get; set; }
        public String profileImageURL { get; set; }
        public String bioSmall { get; set; }
    }
}

demo/Models/DateInput.cs
using System;

namespace demo.Models
{
    public class DateInput
    {
        public String date { get; set; }
    }
}

demo/Models/EventDetails.cs
using System;

namespace demo.Models
{
    public class EventDetails
    {
        public String eventName { get; set; }
        public String lineup { get; set; }
    }
}

demo/Controllers/ArtistController.cs
using demo.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Xml;
using System.Net.Http;
using System.Net.Http.Headers;
using System;
using System.Threading.Tasks;
using System.Linq;

namespace demo.Controllers
{
    public class ArtistController : Controller
    {
        public ActionResult Index(String lineup)
        {
            return View(ParseLineup(lineup));
        }

        public List<string> ParseLineup(string lineup)
        {
            return lineup.Split(',').Select(a => a.Trim()).ToList();
        }

        [HttpGet]
        async public Task<ActionResult> GetArtist(string artistName)
        {
            System.Diagnostics.Debug.WriteLine("Get artist called");
            XmlDocument xd = new XmlDocument();
            xd.LoadXml(await GetArtistDetailsByName(artistName));
            var artistDetails = LoadArtistsFromXml(xd);
            return Json(artistDetails, JsonRequestBehavior.AllowGet);
        }

        private ArtistDetails LoadArtistsFromXml(XmlDocument xd)
        {
            var artistDetails = new ArtistDetails();

            foreach (XmlNode node in xd.SelectNodes("RA/artist"))
            {
                artistDetails = new ArtistDetails
                {
                    djid = int.Parse(node["djid"].InnerText),
                    name = node["artistname"].InnerText,
                    country = node["countryname"].InnerText,
                    labels = node["labels"].InnerText,
                    website = node["website"].InnerText,
                    raProfile = node["raprofile"].InnerText,
                    twitter = node["twitter"].InnerText,
                    facebook = node["facebook"].InnerText,
                    discogs = node["discogs"].InnerText,
                    profileImageURL = node["profileimage"].InnerText,
                    bioSmall = node["biointro"].InnerText,
                };
            }
            return artistDetails;
        }

        async public Task<String> GetArtistDetailsByName(string artistName)
        {
            return await GetRequest("https://www.residentadvisor.net/api/dj.asmx/getartist", "2090605", 
                "a465bde8-ba57-4ce0-95af-923cb856ab9d", "", artistName, "");
        }

        async static Task<String> GetRequest(string url, string userID, string accessKey, string djID,
            string artistName, string artistURL)
        {
            using (HttpClient client = new HttpClient())
            {
                var requestString = url+"?UserID="+userID+"&AccessKey="+accessKey
                    +"&DJID="+djID+"&ArtistName="+artistName+"&URL="+url;

                using (HttpResponseMessage response = await client.GetAsync(requestString))
                {
                    using (HttpContent content = response.Content)
                    {
                        HttpContentHeaders headers = content.Headers;
                        return await content.ReadAsStringAsync();
                    }

                }
            }
        }
    }
}

demo/Controllers/EventController.cs
using demo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace demo.Controllers
{
    public class EventController : Controller
    {
        async public Task<ActionResult> Index(DateInput model)
        {
            XmlDocument xd = new XmlDocument();
            xd.LoadXml(await GetEventsByDate(model.date));
            var events = LoadEventsFromXml(xd);
            return View(LoadEventsFromXml(xd));
        }

        public ActionResult Input()
        {
            return View(new DateInput());
        }

        [HttpPost]
        public ActionResult Date(DateInput model)
        {
            return View();
        }

        private List<EventDetails> LoadEventsFromXml(XmlDocument xd)
        {
            var events = new List<EventDetails>();
            foreach (XmlNode node in xd.SelectNodes("RA/events/event"))
            {
                events.Add(new EventDetails
                {
                    eventName = node["title"].InnerText,
                    lineup = node["lineup"].InnerText,
                });
            }
            return events;
        }

        async public Task<String> GetEventsByDate(string date)
        {
            return await GetRequest("https://www.residentadvisor.net/api/events.asmx/GetEventsByDay", 
                "2090605", "a465bde8-ba57-4ce0-95af-923cb856ab9d", "", "13", date);
        }

        async static Task<String> GetRequest(string url, string userID, string accessKey, string countryID,
            string areaID, string date)
        {
            using (HttpClient client = new HttpClient())
            {
                var requestString = url + "?UserID=" + userID + "&AccessKey=" + accessKey + "&CountryID=" + countryID + "&AreaID=" + areaID + "&Date=" + date;
                using (HttpResponseMessage response = await client.GetAsync(requestString))
                {
                    using (HttpContent content = response.Content)
                    {
                        HttpContentHeaders headers = content.Headers;
                        return await content.ReadAsStringAsync();

                    }

                }
            }
        }
    }
}

demo/Views/Artist/Index.cshtml
@using demo.Models
@model List<string>
@{
    ViewBag.Title = "Index";
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/Styles.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")

</head>
<body>
    <div class="bodyContainer">
        <div class="innerContainer">
            <h3 class="lineupTitle">Line up /</h3>
            <div class="lineupContainer">
                @foreach (var artist in Model)
                {
                    <label class="artists" data-artist-name="@artist" id="@($"modal-opener{artist}")">"@artist" &nbsp/</label>
                }
            </div>
        </div>
    </div>

    <div class="modalContainer" id="dialog-modal" title="Artist Details">
        <table class="table">
            <tr>
                <th></th>
                <td><img id="profileImageUrl" src="" /></td>
            </tr>
            <tr>
                <th>Name</th>
                <td><span id="artistName"></span></td>
            </tr>
            <tr>
                <th>Country</th>
                <td><span id="country"></span></td>
            </tr>
            <tr>
                <th>Labels</th>
                <td><span id="labels"></span></td>
            </tr>
            <tr>
                <th>Website</th>
                <td>
                    <a target="_blank" id="website" href="">
                        
                    </a>
                </td>
            </tr>
            <tr>
                <th>RAProfile</th>
                <td>
                    <a target="_blank" id="raProfile" href="">
                        
                    </a>
                </td>
            </tr>
            <tr>
                <th>Twitter</th>
                <td>
                    <a target="_blank" id="twitter" href="">
                        
                    </a>
                </td>
            </tr>
            <tr>
                <th class="columnWidth1">Facebook</th>
                <td>
                    <a target="_blank" id="facebook" href="">
                        
                    </a>
                </td>
            </tr>
            <tr>
                <th class="columnWidth1">Discogs</th>
                <td>
                    <a target="_blank" id="discogs" href="">
                        
                    </a>
                </td>
            </tr>
            <tr>
                <th>BioSmall</th>
                <td><span id="biosmall"></span></td>
            </tr>
        </table>
    </div>
</body>
</html>

demo/Views/Event/Index.cshtml
@using demo.Models
@model List<EventDetails>
@{
    ViewBag.Title = "Index";
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/Styles.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")

</head>
<body>
    <div class="bodyContainer">
        <div class="innerContainer">
            <h3 class="lineupTitle">Events</h3>
            <div class="lineupContainer">
                @foreach (var eventDetails in Model)
                {
                    <ul>
                        <li>
                            <a href="@Url.Action("Index", "Artist", new {lineup = @eventDetails.lineup})" class="events" data-lineup="@eventDetails.lineup"
                               id="@eventDetails.eventName">@eventDetails.eventName</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
</body>
</html>

demo/Views/Event/Input.cshtml
@using demo.Models
@model DateInput
@{
    ViewBag.Title = "Input";
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/Styles.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")

</head>
<body>
    <div class="bodyContainer">
        @using (Html.BeginForm("Index", "Event"))
        {
            <text>
            Enter date to search for events in london (mm-dd-yyy) : @Html.TextBoxFor(s => s.date)
            <br />
            <br />
            <input type="submit" value="submit" />
            </text>
        }
</div>
</body>
</html>

demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/jquery-ui.js")
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <script>
        $(function () {
            $("#dialog-modal").dialog({
                autoOpen: false,
                show: {
                    effect: "blind",
                    duration: 500
                },
                hide: {
                    effect: "blind",
                    diration: 500
                },
                height: 600,
                width: 700,
                modal: true
            });

            $(".artists").mouseover(function () {   
                var artist = $(this).data('artist-name');
                console.log("artist hovered");
                $.ajax({
                    url: "GetArtist",
                    type: "get",
                    data: { artistName: artist },
                    success: function (data) {
                        displayArtist(data);
                    }
                })
            });

        });

        var displayArtist = function (artist) {
            $('#profileImageUrl').attr('src', artist.profileImageURL);
            $('#artistName').text(artist.name);
            $('#country').text(artist.country);
            $('#website').attr('href', artist.website);
            $('#website').text(artist.website);
            $('#labels').text(artist.labels);

            $('#raProfile').attr('href', artist.raProfile);
            $('#raProfile').text(artist.raProfile);

            $('#twitter').attr('href', 'https://twitter.com/' + artist.twitter);
            $('#twitter').text(artist.twitter);

            $('#facebook').attr('href', 'https://facebook.com/' + artist.facebook);
            $('#facebook').text(artist.facebook);

            $('#discogs').attr('href', 'https://www.discogs.com/artist/' + artist.discogs);
            $('#discogs').text(artist.discogs);

            $('#biosmall').text(artist.bioSmall);
            $("#dialog-modal").dialog("open");
        }

    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>